services:
  - type: web
    name: edutrack-academic
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SCHOOLPULSE_SECRET
        generateValue: true
